apiVersion: v1
kind: ServiceAccount
metadata:
  name: bcf-app
  namespace: blockchain-fintech
  annotations:
    # IRSA: replace with the IAM role ARN created by Terraform (irsa module).
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/blockchain-fintech-app-irsa
